config/routes.rb
Rails.application.routes.draw do
  root 'instituicoes#index'

  resources :instituicoes, except: [:destroy, :show], path_names: {new: "criar", edit: "editar"} do
    member do
      put :arquivar
    end
  end

  resources :repasse_categorias, only: [:create, :destroy, :index] do
    member do
      post :ativar
    end
  end

  resources :categorias, except: [:show, :update], path_names: {new: "criar", edit: "editar" } do
    member do
      post :ativar
    end
  end

  devise_for :usuarios,
    controllers: {registrations: 'usuarios/registrations',
                  confirmations: 'usuarios/confirmations',
  }

  resources :usuarios, except: [:show, :destroy]  do
    member do
      put 'desativar', to: 'usuarios#deactivate'
    end
  end
###################################################################################################################################################
  resources :fusoes
  resources :caboacessos
  resources :uplinks
  resources :fibras do
    get 'conectar'
  end
  resources :tubelooses
  resources :trechos
  resources :incidentes
  resources :caixasubs
  resources :postes
  resources :reservas
  resources :caixaemendas
  resources :segmentos
  resources :jumpers
  resources :dgos do
    resources :portadgos do
      get 'conectar' 
      #get 'conf_conexao'
      post 'conf_conexao'
    end
  end
  resources :portadgos do
    get 'conectar'
  end
  resources :gbics
  resources :porta_slots
  resources :portas_slot
  resources :slots
  resources :switches
  resources :geradores
  resources :nobreaks
  resources :sites
  resources :contatos
  # resources :ipas do
  # 	resources :contatos
  #   resources :sites do
  #     resources :switches do
  #       resources :slots do
  #         resources :porta_slots
  #       end
  #     end
  #   end
  # end

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/models/caixasub.rb
class Caixasub < ApplicationRecord
	belongs_to :reserva, optional: true
	belongs_to :caixaemenda, optional: true
	has_and_belongs_to_many :trechos

end

app/models/conexao.rb
class Conexao < ApplicationRecord
	has_many :fusoes
	belongs_to :site
	belongs_to :caixaemenda
end

app/models/contato.rb
class Contato < ApplicationRecord
	belongs_to :site
end

app/models/dgo.rb
class Dgo < ApplicationRecord
	has_many :portadgos	
	belongs_to :segmento
	has_one :trecho
	has_one :caboacesso
	belongs_to :site
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :responsavel

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :email, format: EMAIL_REGEX, if: :check_email

  protected

  def check_email
    !email.blank?
  end
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :instituicao

  validates :cep, length: {in: 6..15}
end

app/models/fibra.rb
class Fibra < ApplicationRecord
	belongs_to :tubeloose
	has_and_belongs_to_many :caixaemendas
	has_and_belongs_to_many :uplinks
	belongs_to :portadgo
	has_one :fusao

end

app/models/fusao.rb
class Fusao < ApplicationRecord
 belongs_to :fibra
    belongs_to :fibra2, class_name: "Fibra"
    belongs_to :conexao

  # after_create :create_inverse, unless: :has_inverse?
  # after_destroy :destroy_inverses, if: :has_inverse?

  # def create_inverse
  #   self.class.create(inverse_fusao_options)
  # end

  # def destroy_inverses
  #   inverses.destroy_all
  # end

  # def has_inverse?
  #   self.class.exists?(inverse_fusao_options)
  # end

  # def inverses
  #   self.class.where(inverse_fusao_options)
  # end

  # def inverse_jumper_options
  #   { fibra2_id: fibra_id, fibra_id: fibra_id }
  # end
end

app/models/gbic.rb
class Gbic < ApplicationRecord
	belongs_to :porta_slot
	has_many :portadgos
end

app/models/gerador.rb
class Gerador < ApplicationRecord
	belongs_to :site
end

app/models/ipa.rb
class Ipa < ApplicationRecord
	has_many :contatos
	has_many :sites
	has_one :caboacesso
end

app/models/jumper.rb
class Jumper < ApplicationRecord
  belongs_to :portadgo
  belongs_to :portadgo2, class_name: "Portadgo"

  after_create :create_inverse, unless: :has_inverse?
  after_destroy :destroy_inverses, if: :has_inverse?

  def create_inverse
    self.class.create(inverse_jumper_options)
  end

  def destroy_inverses
    inverses.destroy_all
  end

  def has_inverse?
    self.class.exists?(inverse_jumper_options)
  end

  def inverses
    self.class.where(inverse_jumper_options)
  end

  def inverse_jumper_options
    { portadgo2_id: portadgo_id, portadgo_id: portadgo2_id }
  end
end

app/models/nobreak.rb
class Nobreak < ApplicationRecord
	belongs_to :site
end

app/models/poste.rb
class Poste < ApplicationRecord
	belongs_to :reserva, optional: true
	belongs_to :caixaemenda, optional: true
	has_and_belongs_to_many :trechos
end

app/models/reserva.rb
class Reserva < ApplicationRecord
	has_one :poste
	has_one :caixasub
end

app/models/site.rb
class Site < ApplicationRecord
	belongs_to :instituicao
	has_many :geradores
	has_many :nobreaks
	has_many :switches
	has_many :dgos
	has_many :conexoes
end

app/models/slot.rb
class Slot < ApplicationRecord
	belongs_to :switch
	has_many :porta_slots
end

app/models/switch.rb
class Switch < ApplicationRecord
	belongs_to :site
	has_many :slots
end

app/models/trecho.rb
class Trecho < ApplicationRecord
	has_many :incidentes
	belongs_to :segmento
	belongs_to :dgo, optional: true
	has_and_belongs_to_many :caixaemendas
	has_and_belongs_to_many :caixasubs
	has_and_belongs_to_many :postes
	has_many :tubelooses
	belongs_to :caboacesso, optional: true
	scope :por_segmento, -> segmento { where(:segmento => segmento) }
end

app/models/uplink.rb
class Uplink < ApplicationRecord
	has_and_belongs_to_many :fibras

end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :nome, presence: true
  validates :telefone, presence: {alert: "Telefone inválido"}, length: {
    minimum: 8,
    maximum: 13
  }

  def self.all_active
    where(ativo: true)
  end

  def deactivate
    update(ativo: false) unless self.class.where(ativo: true).second.nil?
  end
end

app/controllers/caixasubs_controller.rb
class CaixasubsController < ApplicationController
  before_action :set_caixasub, only: [:show, :edit, :update, :destroy]

  # GET /caixasubs
  # GET /caixasubs.json
  def index
    @caixasubs = Caixasub.all
  end

  # GET /caixasubs/1
  # GET /caixasubs/1.json
  def show
  end

  # GET /caixasubs/new
  def new
    preparar_form
    @caixasub = Caixasub.new
    if params[:reserva]
      @caixasub.reserva = Reserva.find(params[:reserva])
      @caixasub.caixaemenda = nil
    end
    if params[:caixaemenda]
      @caixasub.caixaemenda = Caixaemenda.find(params[:caixaemenda])
    end
  end

  # GET /caixasubs/1/edit
  def edit
    preparar_form
  end

  # POST /caixasubs
  # POST /caixasubs.json
  def create
    @caixasub = Caixasub.new(caixasub_params)

    respond_to do |format|
      if @caixasub.save
        format.html { redirect_to @caixasub, notice: 'Caixasub was successfully created.' }
        format.json { render :show, status: :created, location: @caixasub }
      else
        preparar_form
        format.html { render :new }
        format.json { render json: @caixasub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caixasubs/1
  # PATCH/PUT /caixasubs/1.json
  def update
    preparar_form
    respond_to do |format|
      if @caixasub.update(caixasub_params)
        format.html { redirect_to @caixasub, notice: 'Caixasub was successfully updated.' }
        format.json { render :show, status: :ok, location: @caixasub }
      else
        format.html { render :edit }
        format.json { render json: @caixasub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caixasubs/1
  # DELETE /caixasubs/1.json
  def destroy
    @caixasub.destroy
    respond_to do |format|
      format.html { redirect_to caixasubs_url, notice: 'Caixasub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caixasub
      @caixasub = Caixasub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caixasub_params
      params.require(:caixasub).permit(:cod, :tipo, :infra, :latitude, :longitude, :num_desenho, :tipo_tampa, :reserva_id , :caixaemenda_id)
    end

    def preparar_form
      @reservas = Reserva.order :cod
      @caixaemendas = Caixaemenda.order :cod
    end
end

app/views/caixasubs/_form.html.erb
<%= form_for(caixasub) do |f| %>
  <% if caixasub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caixasub.errors.count, "error") %> prohibited this caixasub from being saved:</h2>

      <ul>
      <% caixasub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cod %>
    <%= f.text_field :cod %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>

  <div class="field">
    <%= f.label :infra %>
    <%= f.text_field :infra %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :num_desenho %>
    <%= f.number_field :num_desenho %>
  </div>

  <div class="field">
    <%= f.label :tipo_tampa %>
    <%= f.text_field :tipo_tampa %>
  </div>
  <% if caixasub.reserva != nil %>
  <div class="field">
    
    <p><%= f.label :reserva_id %><br />
    <%= f.collection_select(:reserva_id, @reservas,:id, :cod, :prompt => true) %></p>
 
  </div>
  <% end %>

  <% if caixasub.caixaemenda != nil %>
  <div class="field">
    
    <p><%= f.label :caixaemenda_id %><br />
    <%= f.collection_select(:caixaemenda_id, @caixaemendas,:id, :cod, :prompt => true) %></p>
 
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caixasubs/edit.html.erb
<h1>Editing Caixasub</h1>

<%= render 'form', caixasub: @caixasub %>

<%= link_to 'Show', @caixasub %> |
<%= link_to 'Back', caixasubs_path %>

app/views/caixasubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Caixasubs</h1>

<table>
  <thead>
    <tr>
      <th>Cod</th>
      <th>Tipo</th>
      <th>Infra</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Num desenho</th>
      <th>Tipo tampa</th>
      <th>Reserva</th>
      <th>Caixa emenda</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caixasubs.each do |caixasub| %>
      <tr>
        <td><%= caixasub.cod %></td>
        <td><%= caixasub.tipo %></td>
        <td><%= caixasub.infra %></td>
        <td><%= caixasub.latitude %></td>
        <td><%= caixasub.longitude %></td>
        <td><%= caixasub.num_desenho %></td>
        <td><%= caixasub.tipo_tampa %></td>
        <td><% if caixasub.reserva != nil %><%= caixasub.reserva.cod %><% end %></td>
        <td><% if caixasub.caixaemenda != nil %><%= caixasub.caixaemenda.cod %><% end %></td>
        <td><%= link_to 'Show', caixasub %></td>
        <td><%= link_to 'Edit', edit_caixasub_path(caixasub) %></td>
        <td><%= link_to 'Destroy', caixasub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caixasub', new_caixasub_path %>

app/views/caixasubs/new.html.erb
<h1>New Caixasub</h1>

<%= render 'form', caixasub: @caixasub %>

<%= link_to 'Back', caixasubs_path %>

app/views/caixasubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cod:</strong>
  <%= @caixasub.cod %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @caixasub.tipo %>
</p>

<p>
  <strong>Infra:</strong>
  <%= @caixasub.infra %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @caixasub.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @caixasub.longitude %>
</p>

<p>
  <strong>Num desenho:</strong>
  <%= @caixasub.num_desenho %>
</p>

<p>
  <strong>Tipo tampa:</strong>
  <%= @caixasub.tipo_tampa %>
</p>

<% if @caixasub.reserva != nil %>
<p>
  <strong>Reserva:</strong>
  <%= @caixasub.reserva.cod %>
</p>
<% end %>

<% if @caixasub.caixaemenda != nil %>
<p>
  <strong>Caixa de Emenda:</strong>
  <%= @caixasub.caixaemenda.cod %>
</p>
<% end %>


<h2>Trechos armazenados: </h2>
<% @caixasub.trechos.each do |t| %>
        <p><%= t.cod %></p>
    <% end %>

<%= link_to 'Edit', edit_caixasub_path(@caixasub) %> |
<%= link_to 'Back', caixasubs_path %>