config/routes.rb
Rails.application.routes.draw do
  root 'instituicoes#index'

  resources :instituicoes, except: [:destroy, :show], path_names: {new: "criar", edit: "editar"} do
    member do
      put :arquivar
    end
  end

  resources :repasse_categorias, only: [:create, :destroy, :index] do
    member do
      post :ativar
    end
  end

  resources :categorias, except: [:show, :update], path_names: {new: "criar", edit: "editar" } do
    member do
      post :ativar
    end
  end

  devise_for :usuarios,
    controllers: {registrations: 'usuarios/registrations',
                  confirmations: 'usuarios/confirmations',
  }

  resources :usuarios, except: [:show, :destroy]  do
    member do
      put 'desativar', to: 'usuarios#deactivate'
    end
  end
###################################################################################################################################################
  resources :fusoes
  resources :caboacessos
  resources :uplinks
  resources :fibras do
    get 'conectar'
  end
  resources :tubelooses
  resources :trechos
  resources :incidentes
  resources :caixasubs
  resources :postes
  resources :reservas
  resources :caixaemendas
  resources :segmentos
  resources :jumpers
  resources :dgos do
    resources :portadgos do
      get 'conectar' 
      #get 'conf_conexao'
      post 'conf_conexao'
    end
  end
  resources :portadgos do
    get 'conectar'
  end
  resources :gbics
  resources :porta_slots
  resources :portas_slot
  resources :slots
  resources :switches
  resources :geradores
  resources :nobreaks
  resources :sites
  resources :contatos
  # resources :ipas do
  # 	resources :contatos
  #   resources :sites do
  #     resources :switches do
  #       resources :slots do
  #         resources :porta_slots
  #       end
  #     end
  #   end
  # end

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/models/caixasub.rb
class Caixasub < ApplicationRecord
	belongs_to :reserva, optional: true
	belongs_to :caixaemenda, optional: true
	has_and_belongs_to_many :trechos

end

app/models/conexao.rb
class Conexao < ApplicationRecord
	has_many :fusoes
	belongs_to :site
	belongs_to :caixaemenda
end

app/models/contato.rb
class Contato < ApplicationRecord
	belongs_to :site
end

app/models/dgo.rb
class Dgo < ApplicationRecord
	has_many :portadgos	
	belongs_to :segmento
	has_one :trecho
	has_one :caboacesso
	belongs_to :site
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :responsavel

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :email, format: EMAIL_REGEX, if: :check_email

  protected

  def check_email
    !email.blank?
  end
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :instituicao

  validates :cep, length: {in: 6..15}
end

app/models/fibra.rb
class Fibra < ApplicationRecord
	belongs_to :tubeloose
	has_and_belongs_to_many :caixaemendas
	has_and_belongs_to_many :uplinks
	belongs_to :portadgo
	has_one :fusao

end

app/models/fusao.rb
class Fusao < ApplicationRecord
 belongs_to :fibra
    belongs_to :fibra2, class_name: "Fibra"
    belongs_to :conexao

  # after_create :create_inverse, unless: :has_inverse?
  # after_destroy :destroy_inverses, if: :has_inverse?

  # def create_inverse
  #   self.class.create(inverse_fusao_options)
  # end

  # def destroy_inverses
  #   inverses.destroy_all
  # end

  # def has_inverse?
  #   self.class.exists?(inverse_fusao_options)
  # end

  # def inverses
  #   self.class.where(inverse_fusao_options)
  # end

  # def inverse_jumper_options
  #   { fibra2_id: fibra_id, fibra_id: fibra_id }
  # end
end

app/models/gbic.rb
class Gbic < ApplicationRecord
	belongs_to :porta_slot
	has_many :portadgos
end

app/models/gerador.rb
class Gerador < ApplicationRecord
	belongs_to :site
end

app/models/ipa.rb
class Ipa < ApplicationRecord
	has_many :contatos
	has_many :sites
	has_one :caboacesso
end

app/models/jumper.rb
class Jumper < ApplicationRecord
  belongs_to :portadgo
  belongs_to :portadgo2, class_name: "Portadgo"

  after_create :create_inverse, unless: :has_inverse?
  after_destroy :destroy_inverses, if: :has_inverse?

  def create_inverse
    self.class.create(inverse_jumper_options)
  end

  def destroy_inverses
    inverses.destroy_all
  end

  def has_inverse?
    self.class.exists?(inverse_jumper_options)
  end

  def inverses
    self.class.where(inverse_jumper_options)
  end

  def inverse_jumper_options
    { portadgo2_id: portadgo_id, portadgo_id: portadgo2_id }
  end
end

app/models/nobreak.rb
class Nobreak < ApplicationRecord
	belongs_to :site
end

app/models/poste.rb
class Poste < ApplicationRecord
	belongs_to :reserva, optional: true
	belongs_to :caixaemenda, optional: true
	has_and_belongs_to_many :trechos
end

app/models/reserva.rb
class Reserva < ApplicationRecord
	has_one :poste
	has_one :caixasub
end

app/models/site.rb
class Site < ApplicationRecord
	belongs_to :instituicao
	has_many :geradores
	has_many :nobreaks
	has_many :switches
	has_many :dgos
	has_many :conexoes
end

app/models/slot.rb
class Slot < ApplicationRecord
	belongs_to :switch
	has_many :porta_slots
end

app/models/switch.rb
class Switch < ApplicationRecord
	belongs_to :site
	has_many :slots
end

app/models/trecho.rb
class Trecho < ApplicationRecord
	has_many :incidentes
	belongs_to :segmento
	belongs_to :dgo, optional: true
	has_and_belongs_to_many :caixaemendas
	has_and_belongs_to_many :caixasubs
	has_and_belongs_to_many :postes
	has_many :tubelooses
	belongs_to :caboacesso, optional: true
	scope :por_segmento, -> segmento { where(:segmento => segmento) }
end

app/models/uplink.rb
class Uplink < ApplicationRecord
	has_and_belongs_to_many :fibras

end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :nome, presence: true
  validates :telefone, presence: {alert: "Telefone inválido"}, length: {
    minimum: 8,
    maximum: 13
  }

  def self.all_active
    where(ativo: true)
  end

  def deactivate
    update(ativo: false) unless self.class.where(ativo: true).second.nil?
  end
end

app/controllers/jumpers_controller.rb
class JumpersController < ApplicationController
  before_action :set_jumper, only: [:show, :edit, :update, :destroy]

  # GET /jumpers
  # GET /jumpers.json
  def index
    @jumpers = Jumper.all
  end

  # GET /jumpers/1
  # GET /jumpers/1.json
  def show
  end

  # GET /jumpers/new
  def new
    preparar_form
    @jumper = Jumper.new
    if params[:portadgo]
      @jumper.portadgo = Portadgo.find(params[:portadgo])
    end
  end

  # GET /jumpers/1/edit
  def edit
  end

  # POST /jumpers
  # POST /jumpers.json
  def create
    @jumper = Jumper.new(jumper_params)

    respond_to do |format|
      if @jumper.save
        format.html { redirect_to @jumper, notice: 'Jumper was successfully created.' }
        format.json { render :show, status: :created, location: @jumper }
      else
        preparar_form
        format.html { render :new }
        format.json { render json: @jumper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jumpers/1
  # PATCH/PUT /jumpers/1.json
  def update
    preparar_form
    respond_to do |format|
      if @jumper.update(jumper_params)
        format.html { redirect_to @jumper, notice: 'Jumper was successfully updated.' }
        format.json { render :show, status: :ok, location: @jumper }
      else
        format.html { render :edit }
        format.json { render json: @jumper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jumpers/1
  # DELETE /jumpers/1.json
  def destroy
    @jumper.destroy
    respond_to do |format|
      format.html { redirect_to jumpers_url, notice: 'Jumper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jumper
      @jumper = Jumper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jumper_params
      params.require(:jumper).permit(:portadgo_id, :portadgo2_id)
    end

    def preparar_form
      @portadgos = Portadgo.order :cod
    end
end

app/views/jumpers/_form.html.erb
<%= form_for(jumper) do |f| %>
  <% if jumper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jumper.errors.count, "error") %> prohibited this jumper from being saved:</h2>

      <ul>
      <% jumper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if @jumper.portadgo %>
      <%= f.hidden_field 'portadgo_id' %>
    <% else %>
    <p><%= f.label :portadgo_id %><br />
    <%= f.collection_select(:portadgo_id, @portadgos,:id, :cod, :prompt => true) %></p>
    <% end %>
  </div>

  <div class="field">
    <p><%= f.label :portadgo2_id %>
    <%= f.collection_select(:portadgo2_id, @portadgos,:id, :cod, :prompt => true) %></p>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jumpers/edit.html.erb
<h1>Editing Jumper</h1>

<%= render 'form', jumper: @jumper %>

<%= link_to 'Show', @jumper %> |
<%= link_to 'Back', jumpers_path %>

app/views/jumpers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jumpers</h1>

<table>
  <thead>
    <tr>
      <th>Portadgo</th>
      <th>Portadgo2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jumpers.each do |jumper| %>
      <tr>
        <td><%= jumper.portadgo.cod %></td>
        <td><%= jumper.portadgo2.cod %></td>
        <td><%= link_to 'Show', jumper %></td>
        <td><%= link_to 'Edit', edit_jumper_path(jumper) %></td>
        <td><%= link_to 'Destroy', jumper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jumper', new_jumper_path %>

app/views/jumpers/new.html.erb
<h1>New Jumper</h1>

<%= render 'form', jumper: @jumper %>

<%= link_to 'Back', jumpers_path %>

app/views/jumpers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Portadgo:</strong>
  <%= @jumper.portadgo.id %>
</p>

<p>
  <strong>Portadgo2:</strong>
  <%= @jumper.portadgo2_id %>
</p>
<%= link_to 'Edit', edit_jumper_path(@jumper) %> |
<%= link_to 'Back', jumpers_path %>