config/routes.rb
Rails.application.routes.draw do
  root 'instituicoes#index'

  resources :instituicoes, except: [:destroy, :show], path_names: {new: "criar", edit: "editar"} do
    member do
      put :arquivar
    end
  end

  resources :repasse_categorias, only: [:create, :destroy, :index] do
    member do
      post :ativar
    end
  end

  resources :categorias, except: [:show, :update], path_names: {new: "criar", edit: "editar" } do
    member do
      post :ativar
    end
  end

  devise_for :usuarios,
    controllers: {registrations: 'usuarios/registrations',
                  confirmations: 'usuarios/confirmations',
  }

  resources :usuarios, except: [:show, :destroy]  do
    member do
      put 'desativar', to: 'usuarios#deactivate'
    end
  end
###################################################################################################################################################
  resources :fusoes
  resources :caboacessos
  resources :uplinks
  resources :fibras do
    get 'conectar'
  end
  resources :tubelooses
  resources :trechos
  resources :incidentes
  resources :caixasubs
  resources :postes
  resources :reservas
  resources :caixaemendas
  resources :segmentos
  resources :jumpers
  resources :dgos do
    resources :portadgos do
      get 'conectar' 
      #get 'conf_conexao'
      post 'conf_conexao'
    end
  end
  resources :portadgos do
    get 'conectar'
  end
  resources :gbics
  resources :porta_slots
  resources :portas_slot
  resources :slots
  resources :switches
  resources :geradores
  resources :nobreaks
  resources :sites
  resources :contatos
  # resources :ipas do
  # 	resources :contatos
  #   resources :sites do
  #     resources :switches do
  #       resources :slots do
  #         resources :porta_slots
  #       end
  #     end
  #   end
  # end

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/models/caixasub.rb
class Caixasub < ApplicationRecord
	belongs_to :reserva, optional: true
	belongs_to :caixaemenda, optional: true
	has_and_belongs_to_many :trechos

end

app/models/conexao.rb
class Conexao < ApplicationRecord
	has_many :fusoes
	belongs_to :site
	belongs_to :caixaemenda
end

app/models/contato.rb
class Contato < ApplicationRecord
	belongs_to :site
end

app/models/dgo.rb
class Dgo < ApplicationRecord
	has_many :portadgos	
	belongs_to :segmento
	has_one :trecho
	has_one :caboacesso
	belongs_to :site
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :responsavel

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :email, format: EMAIL_REGEX, if: :check_email

  protected

  def check_email
    !email.blank?
  end
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :instituicao

  validates :cep, length: {in: 6..15}
end

app/models/fibra.rb
class Fibra < ApplicationRecord
	belongs_to :tubeloose
	has_and_belongs_to_many :caixaemendas
	has_and_belongs_to_many :uplinks
	belongs_to :portadgo
	has_one :fusao

end

app/models/fusao.rb
class Fusao < ApplicationRecord
 belongs_to :fibra
    belongs_to :fibra2, class_name: "Fibra"
    belongs_to :conexao

  # after_create :create_inverse, unless: :has_inverse?
  # after_destroy :destroy_inverses, if: :has_inverse?

  # def create_inverse
  #   self.class.create(inverse_fusao_options)
  # end

  # def destroy_inverses
  #   inverses.destroy_all
  # end

  # def has_inverse?
  #   self.class.exists?(inverse_fusao_options)
  # end

  # def inverses
  #   self.class.where(inverse_fusao_options)
  # end

  # def inverse_jumper_options
  #   { fibra2_id: fibra_id, fibra_id: fibra_id }
  # end
end

app/models/gbic.rb
class Gbic < ApplicationRecord
	belongs_to :porta_slot
	has_many :portadgos
end

app/models/gerador.rb
class Gerador < ApplicationRecord
	belongs_to :site
end

app/models/ipa.rb
class Ipa < ApplicationRecord
	has_many :contatos
	has_many :sites
	has_one :caboacesso
end

app/models/jumper.rb
class Jumper < ApplicationRecord
  belongs_to :portadgo
  belongs_to :portadgo2, class_name: "Portadgo"

  after_create :create_inverse, unless: :has_inverse?
  after_destroy :destroy_inverses, if: :has_inverse?

  def create_inverse
    self.class.create(inverse_jumper_options)
  end

  def destroy_inverses
    inverses.destroy_all
  end

  def has_inverse?
    self.class.exists?(inverse_jumper_options)
  end

  def inverses
    self.class.where(inverse_jumper_options)
  end

  def inverse_jumper_options
    { portadgo2_id: portadgo_id, portadgo_id: portadgo2_id }
  end
end

app/models/nobreak.rb
class Nobreak < ApplicationRecord
	belongs_to :site
end

app/models/poste.rb
class Poste < ApplicationRecord
	belongs_to :reserva, optional: true
	belongs_to :caixaemenda, optional: true
	has_and_belongs_to_many :trechos
end

app/models/reserva.rb
class Reserva < ApplicationRecord
	has_one :poste
	has_one :caixasub
end

app/models/site.rb
class Site < ApplicationRecord
	belongs_to :instituicao
	has_many :geradores
	has_many :nobreaks
	has_many :switches
	has_many :dgos
	has_many :conexoes
end

app/models/slot.rb
class Slot < ApplicationRecord
	belongs_to :switch
	has_many :porta_slots
end

app/models/switch.rb
class Switch < ApplicationRecord
	belongs_to :site
	has_many :slots
end

app/models/trecho.rb
class Trecho < ApplicationRecord
	has_many :incidentes
	belongs_to :segmento
	belongs_to :dgo, optional: true
	has_and_belongs_to_many :caixaemendas
	has_and_belongs_to_many :caixasubs
	has_and_belongs_to_many :postes
	has_many :tubelooses
	belongs_to :caboacesso, optional: true
	scope :por_segmento, -> segmento { where(:segmento => segmento) }
end

app/models/uplink.rb
class Uplink < ApplicationRecord
	has_and_belongs_to_many :fibras

end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :nome, presence: true
  validates :telefone, presence: {alert: "Telefone inválido"}, length: {
    minimum: 8,
    maximum: 13
  }

  def self.all_active
    where(ativo: true)
  end

  def deactivate
    update(ativo: false) unless self.class.where(ativo: true).second.nil?
  end
end

app/controllers/fibras_controller.rb
class FibrasController < ApplicationController
  before_action :set_fibra, only: [:show, :edit, :update, :destroy]

  # GET /fibras
  # GET /fibras.json
  def index
    @fibras = Fibra.all
  end

  # GET /fibras/1
  # GET /fibras/1.json
  def show
  end

  # GET /fibras/new
  def new
    preparar_form
    @fibra = Fibra.new
    if params[:tubeloose]
      @fibra.tubeloose = Tubeloose.find(params[:tubeloose])
    end
  end

  # GET /fibras/1/edit
  def edit
    preparar_form
  end

  # POST /fibras
  # POST /fibras.json
  def create
    @fibra = Fibra.new(fibra_params)

    respond_to do |format|
      if @fibra.save
        format.html { redirect_to @fibra, notice: 'Fibra was successfully created.' }
        format.json { render :show, status: :created, location: @fibra }
      else
        preparar_form
        format.html { render :new }
        format.json { render json: @fibra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fibras/1
  # PATCH/PUT /fibras/1.json
  def update
    preparar_form
    respond_to do |format|
      if @fibra.update(fibra_params)
        format.html { redirect_to @fibra, notice: 'Fibra was successfully updated.' }
        format.json { render :show, status: :ok, location: @fibra }
      else

        format.html { render :edit }
        format.json { render json: @fibra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fibras/1
  # DELETE /fibras/1.json
  def destroy
    @fibra.destroy
    respond_to do |format|
      format.html { redirect_to fibras_url, notice: 'Fibra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def conectar
    preparar_form
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fibra
      @fibra = Fibra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fibra_params
      params.require(:fibra).permit(:tubeloose_id, :numero, :grupo, :cor, :situacao, :proprietario, :info)
    end

    def preparar_form
      @tubelooses = Tubeloose.order :numero
    end
end

app/views/fibras/_fibra.html.erb
<p>
   <%= fibra.numero %>  
   <%= link_to '(remover)', fibra, method: :delete, data: { confirm: 'Are you sure?' } %>
   <%= link_to '(mostrar)', fibra %>
 </p>

app/views/fibras/_form.html.erb
<%= form_for(fibra) do |f| %>
  <% if fibra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fibra.errors.count, "error") %> prohibited this fibra from being saved:</h2>

      <ul>
      <% fibra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if @fibra.tubeloose %>
      <%= f.hidden_field 'tubeloose_id' %>
    <% else %>
    <p><%= f.label :tubeloose_id %><br />
    <%= f.collection_select(:tubeloose_id, @tubelooses,:id, :numero, :prompt => true) %></p>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :numero %>
    <%= f.number_field :numero %>
  </div>

  <div class="field">
    <%= f.label :grupo %>
    <%= f.text_field :grupo %>
  </div>

  <div class="field">
    <%= f.label :cor %>
    <%= f.text_field :cor %>
  </div>

  <div class="field">
    <%= f.label :situacao %>
    <%= f.text_field :situacao %>
  </div>

  <div class="field">
    <%= f.label :proprietario %>
    <%= f.text_field :proprietario %>
  </div>

  <div class="field">
    <%= f.label :info %>
    <%= f.text_field :info %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fibras/conectar.html.erb
<h2>Conectar fibras</h2>

app/views/fibras/edit.html.erb
<h1>Editing Fibra</h1>

<%= render 'form', fibra: @fibra %>

<%= link_to 'Show', @fibra %> |
<%= link_to 'Back', fibras_path %>

app/views/fibras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fibras</h1>

<table>
  <thead>
    <tr>
      <th>Tubeloose</th>
      <th>Numero</th>
      <th>Grupo</th>
      <th>Cor</th>
      <th>Situacao</th>
      <th>Proprietario</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fibras.each do |fibra| %>
      <tr>
        <td><%= fibra.tubeloose.numero %></td>
        <td><%= fibra.numero %></td>
        <td><%= fibra.grupo %></td>
        <td><%= fibra.cor %></td>
        <td><%= fibra.situacao %></td>
        <td><%= fibra.proprietario %></td>
        <td><%= fibra.info %></td>
        <td><%= link_to 'Show', fibra %></td>
        <td><%= link_to 'Edit', edit_fibra_path(fibra) %></td>
        <td><%= link_to 'Destroy', fibra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fibra', new_fibra_path %>

app/views/fibras/new.html.erb
<h1>New Fibra</h1>

<%= render 'form', fibra: @fibra %>

<%= link_to 'Back', fibras_path %>

app/views/fibras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trecho:</strong>
  <%= @fibra.tubeloose.trecho.cod %>
</p>

<p>
  <strong>Tubeloose:</strong>
  <%= @fibra.tubeloose.numero %>
</p>



<p>
  <strong>Numero:</strong>
  <%= @fibra.numero %>
</p>

<p>
  <strong>Grupo:</strong>
  <%= @fibra.grupo %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @fibra.cor %>
</p>

<p>
  <strong>Situacao:</strong>
  <%= @fibra.situacao %>
</p>

<p>
  <strong>Proprietario:</strong>
  <%= @fibra.proprietario %>
</p>

<p>
  <strong>Info:</strong>
  <%= @fibra.info %>
</p>

<p>
  <strong>Porta DGO:</strong>
  <%= @fibra.portadgo.cod %>
</p>

<h2>Caixas de emenda: </h2>
<% @fibra.caixaemendas.each do |t| %>
        <p><%= t.cod %></p>
    <% end %>

  <h2>Uplink: </h2>
<% @fibra.uplinks.each do |t| %>
        <p><%= t.cod %></p>
    <% end %>

<% if @fibra.fusao %>
  <p>
    <strong>Fusão com fibra:</strong>
    <%= @fibra.fusao.fibra2.numero %>
  </p>
<% end %>


<%= link_to "Fazer Fusão", controller: "fusoes", action: "new", fibra: @fibra %>
<%= link_to 'Edit', edit_fibra_path(@fibra) %> |
<%= link_to 'Back', fibras_path %>